# 数据源配置
spring:
    redis:
        database: 1
        host: localhost
        jedis:
            pool:
                #最大连接数据库连接数,设 0 为没有限制
                max-active: 8
                #最大等待连接中的数量,设 0 为没有限制
                max-idle: 8
                #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
                max-wait: -1ms
                #最小等待连接中的数量,设 0 为没有限制
                min-idle: 0
        lettuce:
            pool:
                max-active: 8
                max-idle: 8
                max-wait: -1ms
                min-idle: 0
            shutdown-timeout: 100ms
        port: 6379
    datasource:
        url: jdbc:mysql://localhost:3306/my-demo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        password: 123456
        username: root