server:
  port: 9527
  servlet:
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: utf-8
    # tomcat最大线程数，默认为200
    max-threads: 200
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 25

spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
# 启动jar包时，可通过命令行指定 --spring.profiles.active=prod改变读取的配置文件
  profiles:
    active: dev

  # 文件上传
  servlet:
    multipart:
      max-file-size:  30MB
      max-request-size:  30MB
  # jpa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
#        表名及字段全小写下划线分隔命名策略(默认)
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    open-in-view: false
  # bean可以重复定义，后定义的覆盖前定义的
  main:
    allow-bean-definition-overriding: true

##通用mapper
mapper:
  mappers: com.jin.admin.common.MyBaseMapper
  not-empty: false
  identity: MYSQL
# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.jin.admin.model
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/**/*Mapper.xml
#  驼峰
  configuration:
    map-underscore-to-camel-case: true

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  #  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


# 防止XSS攻击
xss:
  # 过滤开关
  enabled: false
  # 排除链接（多个用逗号分隔）
  excludes:
  # 匹配链接
  urlPatterns:


enable:
  # 校验token
  token: false
# 但设备登录
  single:
    sign: false


